deploy_qa:
  stage: deploy
  script:
    - "[ -d /mnt/odoo-custom-14 ] || sudo mkdir -p /mnt/odoo-custom-14"
    - sudo rm -fr /mnt/odoo-custom-14
    - sudo mkdir -p /mnt/odoo-custom-14
    - sudo cp -r . /mnt/odoo-custom-14
    - sudo chown 101:101 -R /mnt/odoo-custom-14
    - cd /opt/config && docker-compose restart web14 && if [[ "$(docker-compose ps | grep Up | wc -l)" < 2 ]] ; then exit 1; fi
  only:
    - master
  tags:
    - ski-qa-aws

deploy_prod_aws:
  stage: deploy
  script:
    - "[ -d /mnt/odoo-custom-14 ] || sudo mkdir -p /mnt/odoo-custom-14"
    - sudo rm -fr /mnt/odoo-custom-14
    - sudo mkdir -p /mnt/odoo-custom-14
    - sudo cp -r . /mnt/odoo-custom-14
    - sudo chown 101:101 -R /mnt/odoo-custom-14
    - cd /opt/config && docker-compose restart web14 && if [[ "$(docker-compose ps | grep Up | wc -l)" < 2 ]] ; then exit 1; fi
  only:
    - /^Release_Prod.*$/
  except:
    - branches
  tags:
    - saleshfnlife-prod-aws