name: deploy-qa

on:
  push:
    branches:
      - master
env:
  ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
  ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
jobs:
  deploy:
    runs-on: ski-qa-aws
    steps:
      - uses: actions/checkout@v4.2.1
        name: Checkout Code

      - name: restart odoo
        run: |
          sudo rm -fr /mnt/odoo-custom-14
          sudo mkdir -p /mnt/odoo-custom-14
          sudo cp -r . /mnt/odoo-custom-14
          sudo chown 101:101 -R /mnt/odoo-custom-14
          cd /opt/config && docker-compose restart odoo14 && if [[ "$(docker-compose ps | grep Up | wc -l)" < 2 ]] ; then exit 1; fi
